# Generated by Django 4.0.3 on 2022-12-25 18:31

import Users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', Users.models.UserManager()),
            ],
        ),
    ]
