# Generated by Django 4.0.3 on 2022-12-25 21:49

import Users.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('local_atendimento', models.CharField(max_length=255)),
                ('codigo_verificador', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('Users.user',),
            managers=[
                ('objects', Users.models.UserManager()),
            ],
        ),
    ]
