# Generated by Django 4.0.3 on 2022-12-27 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_admin_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='authenticated',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.CreateModel(
            name='AuthenticateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.professional')),
            ],
        ),
    ]
